services:

  mastra:
    build: 
      context: ./mastra
      dockerfile: Dockerfile
    container_name: mastra
    depends_on:
      - db
    ports:
      - "4111:4111"
    env_file:
      - .env.development

  db:
    image: pgvector/pgvector:pg17 # PostgreSQL with pgvector support
    container_name: pgvector-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cesi
      MIGRATION_ENABLED: 'true'
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@adminn.fr
      PGADMIN_DEFAULT_PASSWORD: example
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin

  auth:
    build: 
      context: ./gotrue-1.0.1
      dockerfile: Dockerfile
    container_name: gotrue
    ports:
      - "9999:9999"
    env_file:
      - .env.dev.gotrue

  kong:
    image: kong:latest
    container_name: kong
    ports:
      - "8000:8000"    # Proxy HTTP
      - "8443:8443"    # Proxy HTTPS
      - "8001:8001"    # Admin API HTTP
    environment:
      KONG_DATABASE: "off"  # Mode DB-less (déclaratif)
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    volumes:
      - ./kong.yml:/usr/local/kong/declarative/kong.yml:ro
    depends_on:
      - auth

