services:
  db:
    image: pgvector/pgvector:pg17 # PostgreSQL with pgvector support
    container_name: pgvector-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cesi
      MIGRATION_ENABLED: 'true'
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.fr
      PGADMIN_DEFAULT_PASSWORD: example
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql