services:
  db:
    image: pgvector/pgvector:pg17 # PostgreSQL with pgvector support
    container_name: pgvector-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cesi
      MIGRATION_ENABLED: 'true'
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@adminn.fr
      PGADMIN_DEFAULT_PASSWORD: example
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin

  auth:
    build: 
      context: ./gotrue-1.0.1
      dockerfile: Dockerfile
    container_name: gotrue
    ports:
      - "9999:9999"
    env_file:
      - .env.development